# Generated by Django 3.0.5 on 2020-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookplace',
            name='position',
            field=models.IntegerField(default=9, verbose_name='Позиция на странице очереди'),
        ),
    ]
