# Generated by Django 3.0.5 on 2020-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0003_cookplace_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cook_duration_max',
            field=models.DurationField(blank=True, null=True, verbose_name='Максимальная длительность приготовления одним поваром (обновлять на рабочей панели)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='cook_duration_min',
            field=models.DurationField(blank=True, null=True, verbose_name='Минимальная длительность приготовления одним поваром (обновлять на рабочей панели)'),
        ),
        migrations.AddField(
            model_name='order',
            name='assumed_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемое завершение приготовления заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='assumed_start_cs',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемое начало приготовления части заказа в холодном цехе'),
        ),
        migrations.AddField(
            model_name='order',
            name='assumed_start_hs',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемое начало приготовления части заказа в горячем цехе'),
        ),
        migrations.AddField(
            model_name='order',
            name='cook_duration_cs',
            field=models.DurationField(blank=True, null=True, verbose_name='Предполагаемая длительность приготовления в холодном цеху (вычисляется автоматически)'),
        ),
        migrations.AddField(
            model_name='order',
            name='cook_duration_hs',
            field=models.DurationField(blank=True, null=True, verbose_name='Предполагаемая длительность приготовления в горячем цеху (вычисляется автоматически)'),
        ),
        migrations.AddField(
            model_name='order',
            name='single_shop_flag',
            field=models.BooleanField(blank=True, default=False, verbose_name='Выполнение в одном цехе'),
        ),
    ]
