# Generated by Django 3.0.5 on 2020-05-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0004_auto_20200515_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='mt_steps_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность шагов с пропорциональным увеличением времени (обновлять на рабочей панели)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='table_steps_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность выполнения шагов на производственном столе (обновлять на рабочей панели)'),
        ),
    ]
