# Generated by Django 3.0.5 on 2020-05-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0005_auto_20200516_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='mt_steps_duration',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='table_steps_duration',
        ),
    ]
